### ISSUE TITLE
XSS vulnerability which can steal admin's cookies or more!

### ISSUE THREAD

**Issue by TomAPU** [Verytops/verydows#11]
In page /verydows/index.php?m=api&c=stats&a=count where users'  visiting are logged, we can modify the POST parameter "referrer" which will be shown without filtering to administrator. 
As a result, hacker can construct a XSS payload to steal admin's cookies!
payload:
![2019-02-12-173139_718x576_scrot](https://user-images.githubusercontent.com/44659204/52626149-8a10e280-2eed-11e9-8cb5-35697bc6a83f.png)
result:
![2019-02-12-173211_1031x435_scrot](https://user-images.githubusercontent.com/44659204/52626183-97c66800-2eed-11e9-8ba2-d39cd826e4ac.png)

**Comment by cigery** [comment]
https://github.com/Verytops/verydows/commit/9e87475a9d88f75e7d51f48d514613aea28d1579
