### ISSUE TITLE
Reflected Cross Site Scripting(XSS)-index.php

### ISSUE THREAD

**Issue by wenwill** [Verytops/verydows#12]
Environment installed from  verydows-master

In page localhost/index.php?c=main&a=index, the Get function can change the function used in PHP, the user/attacker can modify the parament and add the script which will be shown without filtering. They can use the script to steal the cookie or some things worse

Payload used: <script>alert(document.cookie)</script>
Affected URL: http://localhost/index.php?c=main&a=index%3Cscript%3Ealert(document.cookie)%3C/script%3E

Navigate to the Affected URL, Payload would be triggered.

Payload used - `<script>alert(document.cookie);</script>`

* Navigate to the Affected URL, Payload would be triggered.
![image](https://user-images.githubusercontent.com/45511549/52755947-a436e780-2ff7-11e9-90e3-e30c44beac5d.png)

**Comment by cigery** [comment]
该问题不存在
