### ISSUE TITLE
安装后访问首页报错

### ISSUE THREAD

**Issue by wuyongguoke** [Verytops/verydows#4]
Database SQL: "SELECT order_id FROM order WHERE (order_status = 1 AND payment_method <> 2) AND created_date <= 1497397978", ErrorInfo: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order WHERE (order_status = 1 AND payment_method <> 2) AND crea' at line 1

**Comment by wuyongguoke** [comment]
MySQL5.5 版本不行？

**Comment by wuyongguoke** [comment]
FROM order 改为 FROM `order` 就不报错了

**Comment by cigery** [comment]
@wuyongguoke  

> FROM order 改为 FROM order 就不报错了

这改动了什么吗？有啥区别？

**Comment by bcbin** [comment]
@cigery ``order``
