### ISSUE TITLE
public/theme/frontend/default/js/general.js 方法重复绑定事件，导致最后确定时多次触发

### ISSUE THREAD

**Issue by jqqjj** [Verytops/verydows#5]
public/theme/frontend/default/js/general.js ： $.fn.vdsConfirm 方法里面的209行，多次调用的话，对button重复绑定事件，以致最后确定的时候触发了N个事件。
解决方法：
应在208行追加一行：
$confirm.find('button').unbind('click');

**Comment by cigery** [comment]
已修正，感谢指出
