### ISSUE TITLE
安装完成提示：将您重定向的次数过多

### ISSUE THREAD

**Issue by zoyzo** [Verytops/verydows#6]
首页及后台都提示同样问题

**Comment by cigery** [comment]
安装完成提示是指的哪一步？ 你安装完install目录下系统有没生成 installed.lock文件？ 根目录index.php代码是什么。最好能贴出来

**Comment by zoyzo** [comment]
![step 2](https://user-images.githubusercontent.com/20568649/30703227-a95ae4cc-9f21-11e7-8cc8-9803b71a11ca.png)
![step 4](https://user-images.githubusercontent.com/20568649/30703231-ae19f0b6-9f21-11e7-85cb-f599fa4437a5.png)
![index php](https://user-images.githubusercontent.com/20568649/30703226-a9553ae0-9f21-11e7-80a1-57945c9f852b.png)

上面安装都是打勾正确，到最后点击访问首页或者后台管理，提示如下错误：
> 该网页无法正常运作

www.a.com 将您重定向的次数过多。
尝试清除 Cookie.
ERR_TOO_MANY_REDIRECTS

**Comment by zoyzo** [comment]
根目录index.php
`<?php
header('Location: ./install/');exit;`

install文件夹也有installed.lock

**Comment by cigery** [comment]
根目录index.php 没有重新生成，所以造成重定向； 正确安装后生成的入口文件index.php里的代码应为：
`<?php
define('APP_DIR', realpath('./'));
defined('DS') or define('DS', DIRECTORY_SEPARATOR);
define('INCL_DIR', APP_DIR.DS.'protected'.DS.'include');
require(INCL_DIR.DS.'core.php');`

**Comment by cigery** [comment]
检查你根目录的写入权限

**Comment by zoyzo** [comment]
按照您说的，赋予了777权限，不过跳回首页和后台提示数据包报错
`Database SQL: "SELECT order_id FROM vi_`$this->table_name` WHERE (order_status = 1 AND payment_method <> 2) AND created_date <= 1506053210", ErrorInfo: Table 'veryinfo.vi_' doesn't exist`

**Comment by zoyzo** [comment]
![index](https://user-images.githubusercontent.com/20568649/30732592-e1159162-9fa5-11e7-8671-d79a1120c2cc.jpg)

**Comment by cigery** [comment]
在GITHUB上下载最版的重新安装，
截图中的问题是之前修复表名保留字问题时引号位置不小心写错了造成的错误，已经修正了：https://github.com/Verytops/verydows/commit/9beae777234599b3cd486478650cda0caf1d145c

**Comment by zoyzo** [comment]
好的，我试一下，谢谢！
